#!/usr/bin/env python3
import os
import shutil
import re
import subprocess
import argparse

if os.getuid() != 0:
	print('Please run with sudo!')
	exit(1)

parser = argparse.ArgumentParser(description='castanet test build')
parser.add_argument('number_of_hosts', type=int, help='The number of random hosts to scan')
args = parser.parse_args()

username = os.environ.get('SUDO_USER')
file_output_path = str(os.path.expanduser(f'~{username}')) + '/castanet_output'

ports: str = '21-25,42,53,80,135-139,443-445,890,1337,1433,1434,1512,3398,5555,8080,9090'

random_scans = subprocess.run(['nmap', '-iR', str(args.number_of_hosts), '-p', ports, '-R', '--open'], check=True, text=True, capture_output=True)


def HostsAreAlive(nmap_output: str) -> bool:
	if re.search("Nmap scan report", nmap_output) == None:
		return False
	return True


def FilterNmapOutput(nmap_output: str) -> str:
	filtered_output: str
	partially_filtered_output: str

	regex_delete_filter = "((Host is up|Not shown|Some closed|Warning).*|Nmap scan report for )"

	partially_filtered_output = re.sub(regex_delete_filter, '', nmap_output)
	filtered_output = os.linesep.join([line for line in partially_filtered_output.splitlines() if line])

	return filtered_output


def main() -> int:
	if HostsAreAlive(random_scans.stdout):
		with open(file_output_path, 'a') as output_file:
			output_file.write(FilterNmapOutput(random_scans.stdout) + '\n')
			shutil.chown(file_output_path, user=username, group=-1)
		return 0
	return 1


if __name__ == '__main__':
	exit(main())