#!/bin/bash
amnt=""
stat=0
ips='21-25,42,53,80,135-139,443-445,890,1337,1433-1434,1512,3398,5555,8080,9090'

[[ -e .net ]] && rm .net
[[ -z $THECATCH ]] && THECATCH=$HOME/casting_the_net/fishing

if [[ -z $1 ]]; then
	while true; do
		echo 'Missing Argument: Number of random hosts to scan'
		echo -n '[amount]: '
		read -r amnt

		if [[ $amnt > 0 ]]; then
			break
		else
			echo 'Bad Input!'
		fi
	done
else
	amnt=$1
fi

timer=0

nmap -T5 -Pn -R -p$ips --open -iR $amnt -oN .net &>/dev/null &

while [[ $(ps | grep nmap) ]]; do
	if [[ $((timer % 3)) == 0 ]]; then
		echo -ne "\e[2K\r\e[1;32m"'[Running]'
	fi
	timer=$((timer + 1))
	echo -ne "\e[1;32m"'.'
	sleep 1
done

sed -re '/(\# Nmap|Host|Not shown|Some closed|Warning)/d' -re 's/Nmap.*for //gm' -i .net

if [[ -n $(cat .net) ]]; then
	cat .net >> $THECATCH
	echo -e "\n\e[1;32;4m$THECATCH populated with new IP addresses!"
	echo -e "\n\e[1;33;4mNew IPs Added:\e[00m"
	grep --color=never -E ".*\(([0-9]+.)+\)" .net
else
	echo -e "\n\e[0;1;41mNo hosts with open ports found\e[0m"
	stat=1
fi

#rm .net
exit $stat